language: go
sudo: false
go:
  - tip
# move to `go mod` should cover this
#before_install:
#  - go get -u github.com/golang/dep/cmd/dep
#  - dep ensure
#  - go get github.com/mattn/goveralls
script:
  # coveralls is giving an error saying it can't find the project.
  # it probably has something to do with Armory vs armory
  # - $GOPATH/bin/goveralls -service=travis-ci
  - go test -v ./...

